CREATE TABLE IF NOT EXISTS usuarios_pendientes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  numero VARCHAR(20) NOT NULL,
  nombre VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  codigo VARCHAR(10) NOT NULL,
  metodo VARCHAR(20) NOT NULL,
  expires BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);